### ISSUE TITLE
Manual Manipulation of Model Weights

### ISSUE THREAD

**Issue by mattebaughman1** [crisbal/docker-torch-rnn#7]
Hi all!

I am wondering if there is an easy way to read in the parameter weights from the .t7 files saved during checkpointing. I want to perform some purely mathematical operations on the weights for a research project, but am unsure of an easy way to access them in raw format as stated. Please let me know!

-Matt

**Comment by crisbal** [comment]
Hello, I am not sure this is an issue with the docker container or with torch-rnn. 

If you need help accessing the files inside the docker I can help, if you need help using these files I don't know enough about it and you should ask here https://github.com/jcjohnson/torch-rnn

**Comment by mattebaughman1** [comment]
You are right, this is not specifically an issue with the docker. I cross-posted this in the main torch-rnn page. I can close the issue. Thank you!
